# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ShortcutsTui < Formula
  desc "A TUI for managing shortcuts"
  homepage "https://github.com/williamtcastro/shortcuts-tui"
  version "1.0.4"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/williamtcastro/shortcuts-tui/releases/download/v1.0.4/shortcuts-tui_1.0.4_darwin_amd64.tar.gz"
      sha256 "ada61e48d128896acc9040c7e4ba5b0e128d9cbdd60555a496d367d04a592ab9"

      def install
        bin.install "shortcuts-tui"
      end
    end
    on_arm do
      url "https://github.com/williamtcastro/shortcuts-tui/releases/download/v1.0.4/shortcuts-tui_1.0.4_darwin_arm64.tar.gz"
      sha256 "4764631feb3f68d229cf55c6ec6d659e3ea60329e0918ffa123b4e095f910e40"

      def install
        bin.install "shortcuts-tui"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/williamtcastro/shortcuts-tui/releases/download/v1.0.4/shortcuts-tui_1.0.4_linux_amd64.tar.gz"
        sha256 "7758223ebe90fc8fd0b1c6dfb41d43529f2e32a93af0ba263f0c1d156630ffc6"

        def install
          bin.install "shortcuts-tui"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/williamtcastro/shortcuts-tui/releases/download/v1.0.4/shortcuts-tui_1.0.4_linux_arm64.tar.gz"
        sha256 "6d90c0c3da3947f2683ce6e94c7b5f6db8b740cd23314196e7b50c86f337d9fc"

        def install
          bin.install "shortcuts-tui"
        end
      end
    end
  end

  test do
    system "#{bin}/shortcuts-tui --help"
  end
end
