# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ShortcutsTui < Formula
  desc "A TUI for managing shortcuts"
  homepage "https://github.com/williamtcastro/shortcuts-tui"
  version "1.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/williamtcastro/shortcuts-tui/releases/download/v1.1.0/shortcuts-tui_1.1.0_darwin_amd64.tar.gz"
      sha256 "92c7f038b0b71d671e566ab6c82858c88aedf0175b6c95d6f450c3fef0785b20"

      def install
        bin.install "shortcuts-tui"
      end
    end
    on_arm do
      url "https://github.com/williamtcastro/shortcuts-tui/releases/download/v1.1.0/shortcuts-tui_1.1.0_darwin_arm64.tar.gz"
      sha256 "f3f1476bf3f3bbf5be7ad363f76130eb2d0837b7e938b27b2240836b4b51ab91"

      def install
        bin.install "shortcuts-tui"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/williamtcastro/shortcuts-tui/releases/download/v1.1.0/shortcuts-tui_1.1.0_linux_amd64.tar.gz"
        sha256 "ecdacb6fc79ab432705d5f14401f6bd45bc2aef1554b1e043b7ad305fb4e6f65"

        def install
          bin.install "shortcuts-tui"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/williamtcastro/shortcuts-tui/releases/download/v1.1.0/shortcuts-tui_1.1.0_linux_arm64.tar.gz"
        sha256 "614d95a9a95ba4334d1364ca94297927278c7e6f8fc962612512899ef4289a77"

        def install
          bin.install "shortcuts-tui"
        end
      end
    end
  end

  test do
    system "#{bin}/shortcuts-tui --help"
  end
end
